version: '3.9'
services:
  nginx:
    image: nginx
    container_name: nginx
    ports:
      - "80:80"
    volumes:
      - ./docker/production/nginx:/etc/nginx/conf.d
    depends_on:
      - app
    links:
      - app

  app:
    build:
      context: .
      dockerfile: ./docker/production/node/Dockerfile
    container_name: server_tarea_4
    restart: on-failure
    volumes:
      - .:/app
      - /app/node_modules
    ports:
      - "3000:3000"